timeout = 20
max_retries = 2
retry_wait_time = 2
exclude_mail = true
exclude_all_private = true
accept = [200, 206, 403, 429]

[remap]
"^/+"   = "https://spike.ist/"
"^@/+"  = "https://spike.ist/"
"^file:///" = "https://spike.ist/"
