name: CI
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  go-build:
    # This job effectively exists to ensure that the code can still be built
    # with the proposed changes.
    name: Go - Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: make build
  go-unit-test:
    name: Go - Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Unit Tests
        run: go test -race -shuffle=on -coverprofile=coverage.txt ./...
  go-vet:
    name: Go - Vet
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Go Vet
        run: go vet ./...