name: Docs Link Check

on:
  pull_request:
    paths:
      - "docs/**"
      - "README.md"
      - ".github/workflows/docs-link-check.yaml"
  push:
    branches: [ main ]
    paths:
      - "docs/**"
      - "README.md"

jobs:
  lychee:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write      # if you want to create issues on broken links
    steps:
      - uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: "--base . --cache --max-cache-age 1d docs README.md"
          format: markdown
          output: ./lychee/out.md
          fail: false # if you want to fail the job on broken links, set to true

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Lychee: Docs Link Report"
          content-filepath: ./lychee/out.md
          labels: "report, links"