name: Docs Link Check

on:
  pull_request:
    paths: ["docs/**", "README.md", ".github/workflows/docs-link-check.yaml"]
  push:
    branches: [main]
    paths: ["docs/**", "README.md"]

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # Important: base-url + only web schemes
          args: >-
            --base-url https://spike.ist
            --cache --max-cache-age 1d
            --timeout 20 --max-retries 2 --retry-wait-time 2
            --accept 200,206,403,429
            docs README.md
          format: markdown
          output: ./lychee/out.md
          fail: false

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: ./lychee/out.md

      # For PRs (Issues are closed)
      - name: Comment on PR with report
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: ./lychee/out.md
