name: Docs Link Check

on:
  workflow_dispatch:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/docs-link-check.yaml"
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/docs-link-check.yaml"

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache lychee
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: lychee-cache-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            lychee-cache-${{ runner.os }}-
      - name: Link check
        uses: lycheeverse/lychee-action@v2
        with:
          args: --cache --max-cache-age 1d --accept 200,206 --verbose ./docs